<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-10-02T08:56:25+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Berlin',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
