<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-10-08T14:14:51+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.4.3',
    'version_db_installed' => '20180716000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1538463384,
        'latest_version' => '8.4.3',
        'do_page_reindex_check' => false,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
